<?xml version="1.0" encoding="utf-8"?>
<Database Name="WorkDB" Class="TraceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=devsqltrans1;Initial Catalog=WorkDB;Integrated Security=True" SettingsObjectName="PKCodeProfiler.Properties.Settings" SettingsPropertyName="WorkDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TestTraceLog" Member="TestTraceLogs">
    <Type Name="TestTraceLog">
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentTick" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GroupKey" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="UserKey" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TraceKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EventDescription" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Parameters" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="TraceOrderBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsException" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MemoryUsage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ticket" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>