#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKCodeProfiler.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="WorkDB")]
	public partial class TraceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TraceDataContext() : 
				base(global::PKCodeProfiler.Properties.Settings.Default.WorkDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TraceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TraceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TraceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TraceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TestTraceLog> TestTraceLogs
		{
			get
			{
				return this.GetTable<TestTraceLog>();
			}
		}
	}
	
	[Table(Name="dbo.TestTraceLog")]
	public partial class TestTraceLog
	{
		
		private string _AssemblyName;
		
		private long _CurrentTick;
		
		private string _GroupKey;
		
		private string _UserKey;
		
		private int _TraceKey;
		
		private System.DateTime _EventDate;
		
		private string _EventType;
		
		private string _EventDescription;
		
		private string _Parameters;
		
		private int _TraceOrderBy;
		
		private bool _IsException;
		
		private int _MemoryUsage;
		
		private string _HostName;
		
		private string _Ticket;
		
		public TestTraceLog()
		{
		}
		
		[Column(Storage="_AssemblyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AssemblyName
		{
			get
			{
				return this._AssemblyName;
			}
			set
			{
				if ((this._AssemblyName != value))
				{
					this._AssemblyName = value;
				}
			}
		}
		
		[Column(Storage="_CurrentTick", DbType="BigInt NOT NULL")]
		public long CurrentTick
		{
			get
			{
				return this._CurrentTick;
			}
			set
			{
				if ((this._CurrentTick != value))
				{
					this._CurrentTick = value;
				}
			}
		}
		
		[Column(Storage="_GroupKey", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string GroupKey
		{
			get
			{
				return this._GroupKey;
			}
			set
			{
				if ((this._GroupKey != value))
				{
					this._GroupKey = value;
				}
			}
		}
		
		[Column(Storage="_UserKey", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string UserKey
		{
			get
			{
				return this._UserKey;
			}
			set
			{
				if ((this._UserKey != value))
				{
					this._UserKey = value;
				}
			}
		}
		
		[Column(Storage="_TraceKey", DbType="Int NOT NULL")]
		public int TraceKey
		{
			get
			{
				return this._TraceKey;
			}
			set
			{
				if ((this._TraceKey != value))
				{
					this._TraceKey = value;
				}
			}
		}
		
		[Column(Storage="_EventDate", DbType="DateTime NOT NULL")]
		public System.DateTime EventDate
		{
			get
			{
				return this._EventDate;
			}
			set
			{
				if ((this._EventDate != value))
				{
					this._EventDate = value;
				}
			}
		}
		
		[Column(Storage="_EventType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EventType
		{
			get
			{
				return this._EventType;
			}
			set
			{
				if ((this._EventType != value))
				{
					this._EventType = value;
				}
			}
		}
		
		[Column(Storage="_EventDescription", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string EventDescription
		{
			get
			{
				return this._EventDescription;
			}
			set
			{
				if ((this._EventDescription != value))
				{
					this._EventDescription = value;
				}
			}
		}
		
		[Column(Storage="_Parameters", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Parameters
		{
			get
			{
				return this._Parameters;
			}
			set
			{
				if ((this._Parameters != value))
				{
					this._Parameters = value;
				}
			}
		}
		
		[Column(Storage="_TraceOrderBy", DbType="Int NOT NULL")]
		public int TraceOrderBy
		{
			get
			{
				return this._TraceOrderBy;
			}
			set
			{
				if ((this._TraceOrderBy != value))
				{
					this._TraceOrderBy = value;
				}
			}
		}
		
		[Column(Storage="_IsException", DbType="Bit NOT NULL")]
		public bool IsException
		{
			get
			{
				return this._IsException;
			}
			set
			{
				if ((this._IsException != value))
				{
					this._IsException = value;
				}
			}
		}
		
		[Column(Storage="_MemoryUsage", DbType="Int NOT NULL")]
		public int MemoryUsage
		{
			get
			{
				return this._MemoryUsage;
			}
			set
			{
				if ((this._MemoryUsage != value))
				{
					this._MemoryUsage = value;
				}
			}
		}
		
		[Column(Storage="_HostName", DbType="NVarChar(100)")]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this._HostName = value;
				}
			}
		}
		
		[Column(Storage="_Ticket", DbType="NVarChar(255)")]
		public string Ticket
		{
			get
			{
				return this._Ticket;
			}
			set
			{
				if ((this._Ticket != value))
				{
					this._Ticket = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
